[package]
name = "bevy_replicon_example_backend"
version = "0.1.0"
description = "A simple transport intended only for examples"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bevy = { version = "0.15", default-features = false }
bevy_replicon = { path = "..", default-features = false }
anyhow = "1.0"

[features]
default = ["client", "server"]
server = ["bevy_replicon/server"]
client = ["bevy_replicon/client"]
